name = "Glass"
uuid = "bb4546cf-ec2a-4cce-80e7-b1aa7c68a867"
authors = ["Dale Black <djblack@uci.edu>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]